// <auto-generated />
using System;
using ApiGestoria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiGestoria.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260922004217_CargaAuto")]
    partial class CargaAuto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiGestoria.Models.CargaAuto", b =>
                {
                    b.Property<int>("CargaAutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargaAutoId"));

                    b.Property<decimal>("Anio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Disponible")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int>("Km")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Patente")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CargaAutoId");

                    b.ToTable("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
